apiVersion: v1
kind: ConfigMap
metadata:
  name: aura-config
data:
  AUTH_DB_NAME: auth_db
  DOCTOR_DB_NAME: doctor_db
  PATIENT_DB_NAME: patient_db
  APPOINTMENT_DB_NAME: appointment_db
  PAYMENT_DB_NAME: payment_db
  NOTIFICATION_DB_NAME: notification_db
  TELEMEDICINE_DB_NAME: telemedicine_db

  AUTH_SERVICE_URL: http://auth-service:5001
  DOCTOR_SERVICE_URL: http://doctor-service:5002
  PATIENT_SERVICE_URL: http://patient-service:5003
  APPOINTMENT_SERVICE_URL: http://appointment-service:5004
  PAYMENT_SERVICE_URL: http://payment-service:5005
  NOTIFICATION_SERVICE_URL: http://notification-service:5006
  TELEMEDICINE_SERVICE_URL: http://telemedicine-service:5007
