apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: aurahealth-appointment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: DB_HOST
              value: appointment-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: aura-config
                  key: APPOINTMENT_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aura-secrets
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_TOKEN
              value: "aura_internal_service_token_2026"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - port: 5004
      targetPort: 5004
  type: ClusterIP
